/**
 * content 도메인(OpenAPI 태그 `content`)의 공개 API. 밖에서는 `@/features/content`로만 가져온다.
 * P3-03: ⑥-1 카피 산출물(getCandidateContentCopy)·⑥-2 고시 원자료(getCandidateContentFact)·열린 ⑥-2 필드 오너 입력
 * (putContentFieldInput) 훅과 카피 편집·사실 표 표시 규칙(model/content). 카피 편집·그대로 유지·완료 뒤 원산지 고치기는
 * `@/features/step-engine`의 `useOwnerEdit`를 쓴다.
 */
export { CONTENT_TAG_KEY, contentKeys } from './api/queryKeys';
export {
  useContentCopyQuery,
  useContentFactQuery,
  usePutContentFieldMutation,
} from './api/content';
export {
  charCount,
  CHOICE_TITLE,
  CHOOSE_GENERATED_LABEL,
  CHOOSE_OWNER_LABEL,
  COPY_EMPTY_TEXT,
  COPY_FIELD_KEYS,
  COPY_FIELD_LABEL,
  COPY_NO_CHANGE_REASON,
  COPY_NOT_EDITABLE_REASON,
  copyDocOf,
  copyEditFields,
  copyFormErrors,
  copyFormOf,
  copyMetaText,
  FACT_EMPTY_TEXT,
  FACT_HEAD_NOTE,
  FACT_KEYS,
  FACT_METHOD_TEXT,
  factField,
  factMetaText,
  factMethodText,
  factSourceText,
  factValueText,
  fieldValueText,
  FIT_AND_SIZE_TITLE,
  HEADLINE_MAX,
  headlineCounter,
  isOwnerField,
  KEEP_AS_IS_DISABLED_REASON,
  KEEP_AS_IS_LABEL,
  MATERIAL_PARTS,
  NO_INFO_TEXT,
  ORIGIN_COUNTRY_REQUIRED_REASON,
  ORIGIN_INPUT_LABEL,
  ORIGIN_NOT_EDITABLE_REASON,
  ORIGIN_SAVE_LABEL,
  ORIGIN_URL_REQUIRED_REASON,
  ORIGIN_WAITING_TEXT,
  originSaveDisabledReason,
  pendingChoices,
  RECHECK_CONFIRM_LABEL,
  RECHECK_LABEL,
  SAVE_COPY_LABEL,
  SELLING_POINTS_MAX,
  SELLING_POINTS_MIN,
  sellingPointsOf,
  sellingPointsText,
  SOURCE_FACTS_TITLE,
} from './model/content';
export type {
  ContentCopyOutput,
  ContentDraftFieldItem,
  ContentFactOutput,
  ContentFieldInputRequest,
  ContentFieldInputResult,
  CopyDoc,
  CopyFieldKey,
  CopyForm,
  CopyFormErrors,
  FactKey,
  OwnerEditFieldInput,
} from './model/content';
